struct HelloWorld
{
	unsigned long index;
	string message;
};


struct HelloWorld_test_2
{
	unsigned long index;
	string message;
	HelloWorld aaaa;
};



struct HelloWorld_test_3
{
    long index;
	string message;
	HelloWorld_test_2 aaa;
	HelloWorld bbb;
};
