struct TimeTest
{
    long sec; 
    unsigned long nanosec; 
};


struct HeaderTest
{
    TimeTest stamp; 
    string frame_id; 
};



struct HelloWorldTest
{
	HeaderTest head;
	string message;
	long index;
};
