// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HelloWorldTypeObject.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "HelloWorld.h"
#include "HelloWorldTypeObject.h"
#include <utility>
#include <sstream>
#include <fastrtps/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>
#include <fastrtps/types/TypeObjectFactory.h>
#include <fastrtps/types/TypeNamesGenerator.h>
#include <fastrtps/types/AnnotationParameterValue.h>
#include <fastcdr/FastBuffer.h>
#include <fastcdr/Cdr.h>

using namespace eprosima::fastrtps::rtps;

void registerHelloWorldTypes()
{
    TypeObjectFactory *factory = TypeObjectFactory::get_instance();
    factory->add_type_object("TimeTest", GetTimeTestIdentifier(true),
    GetTimeTestObject(true));
    factory->add_type_object("TimeTest", GetTimeTestIdentifier(false),
    GetTimeTestObject(false));

    factory->add_type_object("HeaderTest", GetHeaderTestIdentifier(true),
    GetHeaderTestObject(true));
    factory->add_type_object("HeaderTest", GetHeaderTestIdentifier(false),
    GetHeaderTestObject(false));

    factory->add_type_object("HelloWorldTest", GetHelloWorldTestIdentifier(true),
    GetHelloWorldTestObject(true));
    factory->add_type_object("HelloWorldTest", GetHelloWorldTestIdentifier(false),
    GetHelloWorldTestObject(false));

}

const TypeIdentifier* GetTimeTestIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("TimeTest", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetTimeTestObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("TimeTest", complete);
}

const TypeObject* GetTimeTestObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("TimeTest", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteTimeTestObject();
    }
    //else
    return GetMinimalTimeTestObject();
}

const TypeObject* GetMinimalTimeTestObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("TimeTest", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_sec;
    mst_sec.common().member_id(memberId++);
    mst_sec.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_sec.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_sec.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_sec.common().member_flags().IS_OPTIONAL(false);
    mst_sec.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_sec.common().member_flags().IS_KEY(false);
    mst_sec.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_sec.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("int32_t", false));

    MD5 sec_hash("sec");
    for(int i = 0; i < 4; ++i)
    {
        mst_sec.detail().name_hash()[i] = sec_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_sec);

    MinimalStructMember mst_nanosec;
    mst_nanosec.common().member_id(memberId++);
    mst_nanosec.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_nanosec.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_nanosec.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_nanosec.common().member_flags().IS_OPTIONAL(false);
    mst_nanosec.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_nanosec.common().member_flags().IS_KEY(false);
    mst_nanosec.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_nanosec.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint32_t", false));

    MD5 nanosec_hash("nanosec");
    for(int i = 0; i < 4; ++i)
    {
        mst_nanosec.detail().name_hash()[i] = nanosec_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_nanosec);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("TimeTest", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("TimeTest", false);
}

const TypeObject* GetCompleteTimeTestObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("TimeTest", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_sec;
    cst_sec.common().member_id(memberId++);
    cst_sec.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_sec.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_sec.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_sec.common().member_flags().IS_OPTIONAL(false);
    cst_sec.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_sec.common().member_flags().IS_KEY(false);
    cst_sec.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_sec.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("int32_t", false));

    cst_sec.detail().name("sec");

    type_object->complete().struct_type().member_seq().emplace_back(cst_sec);

    CompleteStructMember cst_nanosec;
    cst_nanosec.common().member_id(memberId++);
    cst_nanosec.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_nanosec.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_nanosec.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_nanosec.common().member_flags().IS_OPTIONAL(false);
    cst_nanosec.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_nanosec.common().member_flags().IS_KEY(false);
    cst_nanosec.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_nanosec.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint32_t", false));

    cst_nanosec.detail().name("nanosec");

    type_object->complete().struct_type().member_seq().emplace_back(cst_nanosec);


    // Header
    type_object->complete().struct_type().header().detail().type_name("TimeTest");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("TimeTest", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("TimeTest", true);
}

const TypeIdentifier* GetHeaderTestIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("HeaderTest", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetHeaderTestObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("HeaderTest", complete);
}

const TypeObject* GetHeaderTestObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("HeaderTest", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteHeaderTestObject();
    }
    //else
    return GetMinimalHeaderTestObject();
}

const TypeObject* GetMinimalHeaderTestObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("HeaderTest", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_stamp;
    mst_stamp.common().member_id(memberId++);
    mst_stamp.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_stamp.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_stamp.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_stamp.common().member_flags().IS_OPTIONAL(false);
    mst_stamp.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_stamp.common().member_flags().IS_KEY(false);
    mst_stamp.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_stamp.common().member_type_id(*GetTimeTestIdentifier(false));
    MD5 stamp_hash("stamp");
    for(int i = 0; i < 4; ++i)
    {
        mst_stamp.detail().name_hash()[i] = stamp_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_stamp);

    MinimalStructMember mst_frame_id;
    mst_frame_id.common().member_id(memberId++);
    mst_frame_id.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_frame_id.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_frame_id.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_frame_id.common().member_flags().IS_OPTIONAL(false);
    mst_frame_id.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_frame_id.common().member_flags().IS_KEY(false);
    mst_frame_id.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_frame_id.common().member_type_id(*TypeObjectFactory::get_instance()->get_string_identifier(255, false));


    MD5 frame_id_hash("frame_id");
    for(int i = 0; i < 4; ++i)
    {
        mst_frame_id.detail().name_hash()[i] = frame_id_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_frame_id);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("HeaderTest", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("HeaderTest", false);
}

const TypeObject* GetCompleteHeaderTestObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("HeaderTest", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_stamp;
    cst_stamp.common().member_id(memberId++);
    cst_stamp.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_stamp.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_stamp.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_stamp.common().member_flags().IS_OPTIONAL(false);
    cst_stamp.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_stamp.common().member_flags().IS_KEY(false);
    cst_stamp.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_stamp.common().member_type_id(*GetTimeTestIdentifier(true));
    cst_stamp.detail().name("stamp");

    type_object->complete().struct_type().member_seq().emplace_back(cst_stamp);

    CompleteStructMember cst_frame_id;
    cst_frame_id.common().member_id(memberId++);
    cst_frame_id.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_frame_id.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_frame_id.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_frame_id.common().member_flags().IS_OPTIONAL(false);
    cst_frame_id.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_frame_id.common().member_flags().IS_KEY(false);
    cst_frame_id.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_frame_id.common().member_type_id(*TypeObjectFactory::get_instance()->get_string_identifier(255, false));


    cst_frame_id.detail().name("frame_id");

    type_object->complete().struct_type().member_seq().emplace_back(cst_frame_id);


    // Header
    type_object->complete().struct_type().header().detail().type_name("HeaderTest");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("HeaderTest", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("HeaderTest", true);
}

const TypeIdentifier* GetHelloWorldTestIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("HelloWorldTest", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetHelloWorldTestObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("HelloWorldTest", complete);
}

const TypeObject* GetHelloWorldTestObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("HelloWorldTest", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteHelloWorldTestObject();
    }
    //else
    return GetMinimalHelloWorldTestObject();
}

const TypeObject* GetMinimalHelloWorldTestObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("HelloWorldTest", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_head;
    mst_head.common().member_id(memberId++);
    mst_head.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_head.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_head.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_head.common().member_flags().IS_OPTIONAL(false);
    mst_head.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_head.common().member_flags().IS_KEY(false);
    mst_head.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_head.common().member_type_id(*GetHeaderTestIdentifier(false));
    MD5 head_hash("head");
    for(int i = 0; i < 4; ++i)
    {
        mst_head.detail().name_hash()[i] = head_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_head);

    MinimalStructMember mst_message;
    mst_message.common().member_id(memberId++);
    mst_message.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_message.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_message.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_message.common().member_flags().IS_OPTIONAL(false);
    mst_message.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_message.common().member_flags().IS_KEY(false);
    mst_message.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_message.common().member_type_id(*TypeObjectFactory::get_instance()->get_string_identifier(255, false));


    MD5 message_hash("message");
    for(int i = 0; i < 4; ++i)
    {
        mst_message.detail().name_hash()[i] = message_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_message);

    MinimalStructMember mst_index;
    mst_index.common().member_id(memberId++);
    mst_index.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_index.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_index.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_index.common().member_flags().IS_OPTIONAL(false);
    mst_index.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_index.common().member_flags().IS_KEY(false);
    mst_index.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_index.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("int32_t", false));

    MD5 index_hash("index");
    for(int i = 0; i < 4; ++i)
    {
        mst_index.detail().name_hash()[i] = index_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_index);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("HelloWorldTest", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("HelloWorldTest", false);
}

const TypeObject* GetCompleteHelloWorldTestObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("HelloWorldTest", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_head;
    cst_head.common().member_id(memberId++);
    cst_head.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_head.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_head.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_head.common().member_flags().IS_OPTIONAL(false);
    cst_head.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_head.common().member_flags().IS_KEY(false);
    cst_head.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_head.common().member_type_id(*GetHeaderTestIdentifier(true));
    cst_head.detail().name("head");

    type_object->complete().struct_type().member_seq().emplace_back(cst_head);

    CompleteStructMember cst_message;
    cst_message.common().member_id(memberId++);
    cst_message.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_message.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_message.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_message.common().member_flags().IS_OPTIONAL(false);
    cst_message.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_message.common().member_flags().IS_KEY(false);
    cst_message.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_message.common().member_type_id(*TypeObjectFactory::get_instance()->get_string_identifier(255, false));


    cst_message.detail().name("message");

    type_object->complete().struct_type().member_seq().emplace_back(cst_message);

    CompleteStructMember cst_index;
    cst_index.common().member_id(memberId++);
    cst_index.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_index.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_index.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_index.common().member_flags().IS_OPTIONAL(false);
    cst_index.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_index.common().member_flags().IS_KEY(false);
    cst_index.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_index.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("int32_t", false));

    cst_index.detail().name("index");

    type_object->complete().struct_type().member_seq().emplace_back(cst_index);


    // Header
    type_object->complete().struct_type().header().detail().type_name("HelloWorldTest");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("HelloWorldTest", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("HelloWorldTest", true);
}
